wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.12
    cli_version: 0.23.1
    framework: huggingface
    huggingface_version: 4.57.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1770119726
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 71
      - 84
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 71
      - 84
      - 98
      3:
      - 4
      - 42
      4: 3.12.12
      5: 0.23.1
      6: 4.57.3
      13: linux-x86_64
    e:
      r6gzdx0gn9qksfeugejyvji29q8s1df5:
        os: Linux-5.15.0-139-generic-x86_64-with-glibc2.35
        python: CPython 3.12.12
        started_at: '2026-02-03T11:55:26.154425Z'
        args:
        - --config
        - config/DPO_config_multi_GPU.yaml
        program: /root/HFRL/SurvLLM/DPO.py
        code_path: SurvLLM/DPO.py
        code_path_local: DPO.py
        git:
          remote_url: https://github.com/HollyRiver/HFRL.git
          commit: 2ee5da66cb9ea36bc57a17a9c23f0d9ca09f7733
        root: /root/HFRL/SurvLLM
        host: a2ab04bbb5cc
        executable: /root/anaconda3/envs/LLM/bin/python3.12
        cpu_count: 32
        cpu_count_logical: 64
        gpu_type: NVIDIA L40S
        gpu_count: 2
        disk:
          /:
            total: '3936269393920'
            used: '121244225536'
        memory:
          total: '270126346240'
        gpu_nvidia:
        - name: NVIDIA L40S
          memory_total: '48305799168'
          cuda_cores: 18176
          architecture: Ada
          uuid: GPU-f5b29e30-2d4c-a9be-e61c-a8b28660e522
        - name: NVIDIA L40S
          memory_total: '48305799168'
          cuda_cores: 18176
          architecture: Ada
          uuid: GPU-57fc241b-6801-56b0-5400-2afae706fcb1
        cuda_version: '12.9'
        writer_id: r6gzdx0gn9qksfeugejyvji29q8s1df5
